FROM mysql:5.7.29

ENV MYSQL_DATABASE demo
ENV MYSQL_ROOT_PASSWORD root 
ENV MYSQL_USER demo 
ENV MYSQL_PASSWORD Admin@123
ENV DATABASE_HOST localhost

EXPOSE 3306

#If you have any sql scripts 
#COPY .sql-scripts /docker-entrypoint-initdb.d/ 

